services:
  web:
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "8888:80"
    # volumes:
    #   - ./nginx/public:/usr/share/nginx/html
    depends_on:
      - datasette

  datasette:
    image: windix/datasette:0.64.8
    volumes:
      - data:/data
    command: datasette -p 8001 -h 0.0.0.0 --setting base_url /db/ /data/quiver.db
    depends_on:
      - quiver-converter

  quiver-converter:
    build:
      context: quiver-converter
      dockerfile: Dockerfile
    volumes:
      - data:/data
      - /home/windix/src/quiver/Kmart.qvlibrary:/mnt/quiver

volumes:
  data:
